name: motow_app
description: Motow Chile
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^10.0.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  shared_preferences: ^2.2.0
  rive: ^0.11.11
  flutter_svg: ^2.0.7
  flutter_hooks: ^0.20.0
  cached_network_image: ^3.2.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
  assets:
    - assets/animations/
    - assets/icon/
    - assets/svg/
