name: motow_app
description: Motow Chile
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rive: ^0.9.0
  flutter_svg: ^1.1.1+1
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
  assets:
    - assets/animations/
    - assets/svg/
