// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB61kn4Bq4F_-Xz3iX8Xce848fH32BZxws',
    appId: '1:252166170673:android:30e07aacdba97aaca44d10',
    messagingSenderId: '252166170673',
    projectId: 'motow-app',
    storageBucket: 'motow-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6I8dY8_RNpTlvhHo_VRakNZF0QzTSiik',
    appId: '1:252166170673:ios:cdba25d361d9d8a8a44d10',
    messagingSenderId: '252166170673',
    projectId: 'motow-app',
    storageBucket: 'motow-app.appspot.com',
    iosClientId:
        '252166170673-1adgbkta0oc1j6qa6tcb0ruka0rft13r.apps.googleusercontent.com',
    iosBundleId: 'cl.motow.motowApp',
  );
}
