name: Build & upload an Android App to Firebase App Distribution

on:
  workflow_dispatch:
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Display Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get
        
      - name: Build Android App
        run: flutter build appbundle --release

      - name: Upload Android App to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: build/app/outputs/bundle/release/app-release.aab
