name: Build & upload an Android App to Firebase App Distribution
on:
  workflow_dispatch:
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Display Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get
        
      - name: Build Android App
        run: flutter build appbundle --release

      - name: Update fastlane plugins
        run: fastlane update_plugins
        working-directory: android

      - name: Upload Android App to Firebase App Distribution with fastlane
        run: fastlane appdistribution --verbose
        env:
          ANDROID_APPID: ${{ secrets.FIREBASE_APP_ID }}
          SERVICE_CREDENTIAL: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          APPBUNDLE_PATH: build/app/outputs/bundle/release/app-release.aab
        working-directory: android
