name: Build & upload an Android App to Firebase App Distribution
on: 
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Build Android App
        run: ./gradlew assembleDebug
        working-directory: android